name: bbvi
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - astor=0.7.1
  - blas=1.0
  - bleach=1.5.0
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - cycler=0.10.0
  - dbus=1.13.0
  - expat=2.2.5
  - fontconfig
  - freetype=2.9.1
  - gast=0.2.0
  - gettext=0.19.8.1
  - glib=2.56.2
  - grpcio=1.12.1
  - gst-plugins-base
  - gstreamer
  - h5py=2.8.0
  - hdf5=1.10.2
  - html5lib=0.9999999
  - icu=58.2
  - intel-openmp=2019.0
  - jpeg=9c
  - keras-applications=1.0.6
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libstdcxx-ng=8.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - markdown=3.0.1
  - matplotlib
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.15.0
  - numpy-base=1.15.0
  - openssl=1.0.2p
  - pandas=0.23.4
  - patsy=0.5.1
  - pcre=8.41
  - pip=18.1
  - protobuf=3.6.1
  - pthread-stubs=0.4
  - pyparsing=2.3.0
  - pyqt
  - python=3.6.6
  - python-dateutil=2.7.5
  - pytz=2018.7
  - qt=5.6.2
  - readline=7.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.5.0
  - sip=4.18.1
  - six=1.11.0
  - sqlite
  - statsmodels=0.9.0
  - tensorboard=1.7.0
  - tensorflow=1.7.0
  - tensorflow-base=1.7.0
  - termcolor=1.1.0
  - tk
  - tornado=5.1.1
  - werkzeug=0.14.1
  - wheel=0.32.2
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - sklearn
  - pip:
    - colorama==0.4.0
    - edward==1.3.5

